### ISSUE TITLE
Add feature/ability to pass in existing resources instead of assume creation from zero

### ISSUE THREAD

**Issue by tbowman-bah** [hashicorp/terraform-aws-terraform-enterprise#284]
**What problem would you like to address?**
Take a govcloud deployment for example.  In govcloud, the project may not be able to create VPC or other resources.  The govcloud governance and cloud service provider may create those resources for the project.  I would like to be able to pass those values in and instead of the module creating the resource, consume the given resource.  ie.  vpc_id, public_subnets, or IAM_role

**Who is the audience for this request?**
The end users are initially a govcloud user, but could be any cloud tenant depending on governance.

**What would the ideal solution look like?**
If the resource has been provided then consume the resource.  If the resource is not provided, attempt to create the resources as currently designed to do.

**What alternatives have you considered?**
A. Writing our own modules. 
B. Tearing apart the current upstream deployment to perform resource creation using a different IAM roles.  

**How does this impact you?**
We cannot create iam roles/policies due to govcloud and company governance policies.
We have been working to provide values to each of the services and implement a count in the resources to check if provided.

**Are there any deadlines?**
1 May 2023

**Is there any additional context?**
Govcloud account

**Comment by anniehedgpeth** [comment]
Hi @tbowman-bah , thanks for the feature request! 

I'm happy to tell you that part of this functionality is already available within this module. If you provide the [variables for the network details](https://github.com/hashicorp/terraform-aws-terraform-enterprise/blob/main/variables.tf#L277-L319), you should be able to use your own VPC. This is an [example](https://github.com/hashicorp/terraform-aws-terraform-enterprise/tree/main/examples/existing-network) implementation of bring your own VPC.

As far as the IAM Role goes, are you referring to the `aws_iam_role.instance_role` [here](https://github.com/hashicorp/terraform-aws-terraform-enterprise/blob/main/modules/service_accounts/main.tf#L9-L12) that is created for the TFE instance to be able to read from the Secrets Manager? You would like to bring your own instead of creating one?

**Comment by tbowman-bah** [comment]
Our current governance, combined with govcloud configurations, prevents us from creating roles.  We can request to have iam roles created and policies assigned but are unable to implement via TF code.

**Comment by anniehedgpeth** [comment]
Good new, @tbowman-bah , we've added this feature request to our backlog and plan to implement it in the near future, hopefully well before your deadline. Thank you!

**Comment by anniehedgpeth** [comment]
I believe that #285 closes this feature request. Thank you!
